# Generated by Django 5.1.3 on 2024-12-07 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='oauth_provider',
        ),
        migrations.RemoveField(
            model_name='user',
            name='oauth_uid',
        ),
    ]
